[project]
name = "aoc_2023"
version = "0.0.0"
dependencies = ["advent-of-code-data"]
requires-python = ">=3.11"

[project.optional-dependencies]
lint = ["shed", "isort", "black"]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
